version: '3'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rest_api
    ports:
      - 3306:3306

volumes:
  db-data:
